In [129]:
import numpy as np
import pandas as pd

In [130]:
# loading dataset
df = pd.read_excel("./Data/Ecommerce_Unclean_Project.xlsx")

## Data Assessing

### Issues with Dataset

1. **Dirty Data** 

Table Name: `Ecommerce_Unclean`
- Initially: 524 rows, 15 columns
- Incorrect data types in Order_Date, Delivery_Date, and Discount : `Validity`
- Missing values in Phone (22), Qty (67), Unit_Price (53), Discount (69), and Delivery_Date (21) : `Completeness`
- 11 duplicated rows : `Uniqueness`
- Replace invalid missing-value representations (NaN, blank, N/A) with proper NaN values : `Completeness`
- Remove extra leading and trailing spaces from object-type columns : `Consistency`
- Standardize text formats in Customer_Name, City, and State : `Consistency`
- Validate email addresses against the expected email format : `Validity`
- Identified invalid Qty values (zero and negative quantities) : `Validity`

2. **Messy Data**
   
   Table Name: `Ecommerce_Unclean`
- `None`

In [131]:
df.shape

(524, 15)

In [132]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [133]:
df.sample(5)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
353,ORD1355,10-03-2025,Sneha,sneha18@gmail.com,9.117422e+09,Mumbai,Maharashtra,Watch,Fashion,4.0,999.0,15,Wallet,Pending,20-03-2025
97,ORD1099,2025/03/12,Rahul,rahul62@gmail.com,9.409139e+09,Lucknow,UP,Bottle,Home,1.0,499.0,0,UPI,Pending,15-03-2025
192,ORD1194,17-05-2025,Neha,neha48@gmail.com,9.251581e+09,Bengaluru,Karnataka,Laptop,Electronics,5.0,1499.0,NaN,Card,Delivered,27-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
374,ORD1376,01-06-2025,Sneha,sneha34@gmail.com,9.409847e+09,Lucknow,UP,Mouse,Electronics,4.0,999.0,NaN,COD,Delivered,11-06-2025

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [135]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [136]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [137]:
df.duplicated().sum()

np.int64(11)

In [138]:
df['City'].value_counts()

City
Pune          98
Mumbai        94
Bengaluru     84
Lucknow       79
Jaipur        73
Delhi         69
Mumbai         7
Pune           6
Bengaluru      5
Delhi          5
Jaipur         2
Lucknow        2
Name: count, dtype: int64

In [139]:
# invalid emails
df['Email'][~df['Email'].str.contains('@', na=False)]

29     sneha76gmail.com
60      amit18gmail.com
91     priya20gmail.com
122    rahul45gmail.com
153     amit98gmail.com
184    vikas44gmail.com
215      neha6gmail.com
246    priya58gmail.com
277    sneha86gmail.com
308      amit7gmail.com
339    rahul93gmail.com
370    rahul15gmail.com
401    rohit30gmail.com
432    vikas94gmail.com
463    priya27gmail.com
494     amit43gmail.com
Name: Email, dtype: object

## Data Cleaning

In [140]:
# Remove duplicates
df.drop_duplicates(inplace=True)

In [141]:
df.duplicated().sum()

np.int64(0)

In [142]:
# Replace common invalid values with NaN
df.replace(['N/A', 'NULL', ''], np.nan, inplace=True)

In [143]:
# Remove extra spaces
df = df.apply(lambda x : x.str.strip() if x.dtype == 'object' else x).copy()

In [144]:
# Standardize text format
# Convert text into Proper case

cols = ['Customer_Name', 'City', 'State']

for i in cols:
    df[i] = df[i].str.title()

In [145]:
# Validate 'Email'
# Keep only valid email records

df = df[df['Email'].str.contains('@', na=False)]

In [146]:
# Remove invalid 'Qty' (negative or zero)

df = df[df['Qty']>0]

In [147]:
# Convert date columns

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce', dayfirst=True)
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], errors='coerce', dayfirst=True)

In [148]:
# Convert numeric columns

cols = ['Qty', 'Unit_Price', 'Discount']

for i in cols:
    df[i] = pd.to_numeric(df[i], errors='coerce')

In [149]:
# Filling Missing Values

df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(0)

## Feature Engineering

In [150]:
# Sales

df['Sales'] = df['Qty']*df['Unit_Price']

In [151]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03 00:00:00,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09 00:00:00,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08 00:00:00,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18 00:00:00,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27 00:00:00,39996.0

In [152]:
# Net Amount

df['Net_Amount'] = df['Sales'] - (df['Sales']*df['Discount'])

In [153]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03 00:00:00,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09 00:00:00,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08 00:00:00,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18 00:00:00,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27 00:00:00,39996.0,39996.0

In [154]:
# Profit (Assuming 20%)

df['Profit'] = df['Net_Amount']*0.20

In [155]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03 00:00:00,7996.0,7996.0,1599.2
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09 00:00:00,24995.0,24995.0,4999.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08 00:00:00,5997.0,5997.0,1199.4
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18 00:00:00,1497.0,1497.0,299.4
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27 00:00:00,39996.0,39996.0,7999.2

In [156]:
# Order Month
df['Month'] = df['Order_Date'].dt.month_name()

In [157]:
# Year
df['Year'] = df['Order_Date'].dt.year

In [158]:
# Weekday
df['Weekday'] = df['Order_Date'].dt.day_name()

## Final Data Validation

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       380 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          380 non-null    object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  380 non-null    object
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    object
 19  Year           333 non-null    float64
 20  Weekday        333 non-null    object
dtypes: datetime64[ns](1), float64(7), object(13)
memory usage: 65.3+ KB

In [160]:
df.isnull().sum()

Order_ID          0
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     0
Sales            37
Net_Amount       37
Profit           37
Month            47
Year             47
Weekday          47
dtype: int64

In [161]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Sales,Net_Amount,Profit,Year
count,333,380.000000,343.000000,380.0,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108032,3.328947,3252.352770,0.0,11103.664723,11103.664723,2220.732945,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.0,499.000000,499.000000,99.800000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.0,2599.000000,2599.000000,519.800000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,0.0,5997.000000,5997.000000,1199.400000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,0.0,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,0.0,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,0.0,12194.528486,12194.528486,2438.905697,0.0

In [163]:
df.shape

(380, 21)

## Exporting Clean Data

In [162]:
df.to_csv('Ecmmerce_Clean.csv', index=False)

## Importing data into MySQL

In [169]:
from sqlalchemy import create_engine
import pandas as pd

In [170]:
engine = create_engine("mysql+pymysql://root:%40Anish%23123@localhost:3306/ecommerce")

# export dataframe to MySQL
df = pd.read_csv("./Data/Ecommerce_Clean.csv")
df.to_sql(
    name="orders",                # table name
    con=engine,                   # connection
    if_exists="replace",          # 'fail', 'replace', 'append'
    index=False                   # don’t add pandas index column
)

380